// UI chrome is multilingual (English / Telugu / Hindi) to demonstrate the multilingual
// architecture end-to-end. Generated legal answers are translated live via
// the backend's translation pipeline (see backend/app/translate.py); if that
// service is unreachable, the UI shows a visible "translation unavailable"
// note rather than silently displaying the wrong language.
export const COPY = {
  en: {
    appName: 'SUTRADHARA',
    tagline: 'AI-Powered IP & Regulatory Intelligence for Ayurveda',
    team: 'Team Chaturya',
    heroLede:
      'The platform connects Ayurvedic products with applicable intellectual-property regimes, regulatory requirements, jurisdiction-specific rules, and authoritative evidence.',
    heroCta: 'Analyze an Ayurvedic Product',

    navAnalyze: 'Analyze',
    navAbs: 'ABS Compliance',
    navTkdl: 'TKDL Check',
    navEvidence: 'Evidence',
    navGraph: 'Knowledge Graph',
    navEval: 'Evaluation',

    inputLabel: 'Describe your Ayurvedic product or IP question',
    placeholder: 'e.g. Can I patent a classical Ayurvedic formulation already described in a traditional text?',
    analyze: 'Analyze',
    analyzing: 'Analyzing…',
    india: 'India',
    international: 'International',
    disclaimer: 'Information, not legal advice.',
    classification: 'Product Classification',
    jurisdiction: 'Jurisdiction',
    applicableAreas: 'Applicable IP & Regulatory Areas',
    assessment: 'AI Assessment',
    sources: 'Evidence & Citations',
    confidence: 'Evidence Confidence',
    escalate: 'Escalate to IP Facilitator',
    needExpert: 'Need expert assistance?',
    detectedLanguage: 'Detected input language',
    retrievalNote: 'Retrieval normalized to',
    evidenceBoundary: 'Evidence Boundary',
    evidenceBoundaryBody: 'Insufficient authoritative evidence to provide a reliable answer.',
    whyAbstained: 'Why the system abstained',
    systemError: 'Analysis service temporarily unavailable. Please try again in a moment.',

    evidencePageTitle: 'Evidence Explorer',
    evidencePageLede: 'Where did the last answer come from? Every source below was actually retrieved from the authoritative corpus for your most recent analysis — nothing here is invented.',
    evidenceEmpty: 'Run an analysis first — retrieved sources for that query will appear here.',

    graphEmpty: 'Knowledge graph data is unavailable from the backend right now.',
    evalEmpty: 'No queries logged yet in this session.',


    absTitle: 'ABS Compliance Check',
    absLede: 'Checks whether a query is likely to trigger Access-and-Benefit-Sharing obligations under the Biological Diversity Act, CBD, and the Nagoya Protocol — and what evidence supports that.',
    absPlaceholder: 'e.g. We want to commercialize a formulation using a biological resource sourced from a specific region in India',
    absButton: 'Check ABS Compliance',
    absEmpty: 'Describe the product or sourcing scenario above to see the ABS checklist here.',
    absNotTriggered: 'No clear Access-and-Benefit-Sharing signal was found for this query. This does not rule ABS out — describe the biological resource and its provenance for a more specific check.',

    tkdlTitle: 'TKDL / Prior-Art Check',
    tkdlLede: 'Points to the Traditional Knowledge Digital Library workflow relevant to a classical formulation, and surfaces the prior-art sources the system found.',
    tkdlPlaceholder: 'e.g. Is this formulation already documented as traditional knowledge in a classical text?',
    tkdlButton: 'Check TKDL / Prior Art',
    tkdlEmpty: 'Describe the formulation above to see the Traditional Knowledge pointer and related sources here.',
    tkdlNotTriggered: 'No Traditional Knowledge pointer was generated for this query — it may not be classified as classical/generic, or no TK-related source was retrieved.',

    languageEnglish: 'English', languageTelugu: 'తెలుగు', languageHindi: 'हिन्दी', primaryNavigation: 'Primary navigation', loadingAnalysis: 'Loading analysis',
    analysisHelper: 'Source-grounded analysis across the selected jurisdiction', jurisdictionPrefix: 'JURISDICTION',
    clarificationCategories: ['Classical / Generic Medicine', 'Patent / Proprietary Medicine', 'New / Non-Classical Drug', 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical', 'Cosmetic'],
    paraphraseVerified: 'phrased via Groq · citations verified', translationUnavailableAnswer: 'Translation service unavailable right now — showing the English answer.',
    tkPointer: 'Traditional Knowledge / Prior-Art Pointer', absConsiderations: 'Potential ABS Considerations',
    absChecklist: { biologicalResource: 'Biological resource involved', provenance: 'Source/provenance identified', framework: 'Relevant ABS framework identified', source: 'Supporting source retrieved' },
    confidenceSupport: 'How strongly the retained sources support this analysis', compositeConfidence: 'composite confidence', confidenceScale: 'confidence scale',
    confidenceFactors: { retrieval_relevance: 'Retrieval relevance', source_count_factor: 'Source count', source_authority: 'Source authority', agreement: 'Domain agreement', classification_confidence: 'Classification confidence' },
    confidenceNote: 'Composite score computed from retrieval and classification signals actually produced by this analysis — never a fabricated accuracy figure.',
    translationUnavailableMessage: 'Translation service unavailable right now — showing the English message.', evidenceBoundaryReason: 'The retained evidence set was empty or its combined confidence fell below the safe-answer threshold — so the system is declining to answer rather than guess.',
    sourceLabel: 'SOURCE', matchLabel: 'match', sourceFields: { authority: 'Authority', domain: 'Domain', type: 'Source type', version: 'Version', retrieved: 'Retrieved', precision: 'Precision' }, viewSource: 'View source',
    builtFor: 'Built for the Ministry of AYUSH & All India Institute of Ayurveda', liveEvidenceTrail: 'A live evidence trail', heroTraceTitle: 'From product to provision, with the chain visible.', heroTraceBody: 'SUTRADHARA classifies the question, routes the relevant regime, and keeps the source in view.', citationGrounded: 'Citation-grounded by design',
    heroTrace: [{ label: 'Product query', value: 'Ashwagandha extract with a novel process' }, { label: 'Classification', value: 'Phytopharmaceutical / biological resource' }, { label: 'Evidence route', value: 'Biological Diversity Act, 2002 · Section 7' }], sourceRetained: 'Source retained', confidenceHigh: 'Confidence: high',
    focusedTool: 'Focused research tool', working: 'Working…', absChecklistLabel: 'ABS checklist', tkdlPointerLabel: 'TKDL pointer', preview: 'preview',
    reviewPathway: 'Human review pathway', escalateTitle: 'Escalate to IP Facilitator', escalationDescription: 'A human facilitator will review this query along with the evidence retrieved below.', escalationRecorded: 'Escalation recorded.', escalationFollowUp: 'A facilitator will follow up using the context below.',
    escalationFields: { query: 'Query', category: 'Category', jurisdiction: 'Jurisdiction', areas: 'Areas', sources: 'Sources' }, noSources: 'none', contactEmail: 'Contact email (optional)', emailPlaceholder: 'you@example.com', escalationError: 'Could not reach the escalation service — please try again.', cancel: 'Cancel', sending: 'Sending…', submit: 'Submit',
    graphGrounding: 'How the answer is grounded', explainabilityGraph: 'Explainability Graph', graphLegend: { query: 'Query context', regulatory: 'Regulatory structure', traditional: 'Traditional knowledge', authoritative: 'Authoritative source' },
    classificationCategories: { 'Classical / Generic Medicine': 'Classical / Generic Medicine', 'Patent / Proprietary Medicine': 'Patent / Proprietary Medicine', 'New / Non-Classical Drug': 'New / Non-Classical Drug', Phytopharmaceutical: 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical': 'Ayurveda-Aahar / Nutraceutical', Cosmetic: 'Cosmetic' }, areaLabels: { Patents: 'Patents', 'Geographical Indications': 'Geographical Indications', Trademarks: 'Trademarks', Copyright: 'Copyright', Designs: 'Designs', 'Trade Secrets': 'Trade Secrets', 'Plant Variety Protection': 'Plant Variety Protection', 'Traditional Knowledge': 'Traditional Knowledge', 'Access-and-Benefit-Sharing': 'Access-and-Benefit-Sharing', 'Drug regulation': 'Drug regulation', Advertising: 'Advertising', Labelling: 'Labelling', 'Food / nutraceutical regulation': 'Food / nutraceutical regulation', 'Cosmetic regulation': 'Cosmetic regulation' },
    graphNodes: { product: 'Ayurvedic Product', category: 'Product Category', tk: 'Traditional Knowledge', regime: 'IP/Regulatory Regime', law: 'Governing Law', provision: 'Provision', source: 'Authoritative Source' }, graphEdges: { product_category: 'belongs to', category_regime: 'relevant to', category_tk: 'may reference', regime_law: 'governed by', law_provision: 'contains', provision_source: 'supported by' },
    eval: { observability: 'System observability', title: 'Evaluation Dashboard', chartLabel: 'Confidence history chart', chartTitle: 'Confidence over logged queries', observations: 'observations', chartEmpty: 'Confidence history will trace here after the first analysis.', queryStart: 'query 01', queryLatest: 'latest query', totalQueries: 'Total queries logged', safeAbstention: 'Safe-abstention rate', averageConfidence: 'Average confidence', answerAccuracy: 'Answer accuracy', citationCorrectness: 'Citation correctness', classificationAccuracy: 'Classification accuracy', multilingualQuality: 'Multilingual response quality', pending: 'Evaluation pending', manualReviewSet: 'Evaluation pending — requires manual review against the verified test set', manualReview: 'Evaluation pending — requires manual review', emptyTitle: 'Your evidence trail starts here.', emptyBody: 'Run an analysis to populate confidence history, citation checks, and classification review.', citationReview: 'citation review', note: 'Evaluation pending — no queries logged yet.' },
  },
  te: {
    appName: 'సూత్రధార',
    tagline: 'ఆయుర్వేదం కోసం AI-ఆధారిత మేధో సంపత్తి & నియంత్రణ మేధస్సు',
    team: 'టీమ్ చతుర్య',
    heroLede:
      'ఈ వేదిక ఆయుర్వేద ఉత్పత్తులను వర్తించే మేధో సంపత్తి పాలనలు, నియంత్రణ అవసరాలు, అధికార-పరిధి నిర్దిష్ట నియమాలు మరియు అధికారిక ఆధారాలతో అనుసంధానిస్తుంది.',
    heroCta: 'ఆయుర్వేద ఉత్పత్తిని విశ్లేషించండి',

    navAnalyze: 'విశ్లేషణ',
    navAbs: 'ABS అనుసరణ',
    navTkdl: 'TKDL పరిశీలన',
    navEvidence: 'ఆధారాలు',
    navGraph: 'జ్ఞాన గ్రాఫ్',
    navEval: 'మూల్యాంకనం',

    inputLabel: 'మీ ఆయుర్వేద ఉత్పత్తి లేదా IP ప్రశ్నను వివరించండి',
    placeholder: 'ఉదా. సాంప్రదాయ గ్రంథంలో వివరించిన శాస్త్రీయ ఆయుర్వేద సూత్రీకరణకు నేను పేటెంట్ పొందవచ్చా?',
    analyze: 'విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది…',
    india: 'భారతదేశం',
    international: 'అంతర్జాతీయ',
    disclaimer: 'ఇది సమాచారం మాత్రమే, న్యాయ సలహా కాదు.',
    classification: 'ఉత్పత్తి వర్గీకరణ',
    jurisdiction: 'అధికార పరిధి',
    applicableAreas: 'వర్తించే IP & నియంత్రణ అంశాలు',
    assessment: 'AI మదింపు',
    sources: 'ఆధారాలు & ఉల్లేఖనలు',
    confidence: 'ఆధార విశ్వసనీయత',
    escalate: 'IP సదుపాయకుడికి తెలియజేయండి',
    needExpert: 'నిపుణుల సహాయం కావాలా?',
    detectedLanguage: 'గుర్తించిన ఇన్‌పుట్ భాష',
    retrievalNote: 'రిట్రీవల్ కోసం సాధారణీకరించబడింది',
    evidenceBoundary: 'ఆధార పరిమితి',
    evidenceBoundaryBody: 'నమ్మదగిన సమాధానం ఇవ్వడానికి తగినంత అధికారిక ఆధారాలు లేవు.',
    whyAbstained: 'వ్యవస్థ ఎందుకు నిరాకరించింది',
    systemError: 'విశ్లేషణ సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.',

    evidencePageTitle: 'ఆధార అన్వేషణ',
    evidencePageLede: 'చివరి సమాధానం ఎక్కడ నుండి వచ్చింది? మీ ఇటీవలి విశ్లేషణ కోసం క్రింద ఉన్న ప్రతి మూలం అధికారిక కార్పస్ నుండి నిజంగా పొందబడింది.',
    evidenceEmpty: 'ముందుగా ఒక విశ్లేషణ నడపండి — ఆ ప్రశ్న కోసం పొందిన మూలాలు ఇక్కడ కనిపిస్తాయి.',

    graphEmpty: 'ప్రస్తుతం బ్యాకెండ్ నుండి నాలెడ్జ్ గ్రాఫ్ డేటా అందుబాటులో లేదు.',
    evalEmpty: 'ఈ సెషన్‌లో ఇంకా ప్రశ్నలు నమోదు కాలేదు.',


    absTitle: 'ABS అనుసరణ పరిశీలన',
    absLede: 'జీవవైవిధ్య చట్టం, CBD మరియు నాగోయా ప్రోటోకాల్ కింద యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ బాధ్యతలను ప్రశ్న ప్రేరేపించే అవకాశం ఉందో లేదో పరిశీలిస్తుంది.',
    absPlaceholder: 'ఉదా. భారతదేశంలోని ఒక నిర్దిష్ట ప్రాంతం నుండి పొందిన జీవ వనరును ఉపయోగించి సూత్రీకరణను వాణిజ్యీకరించాలనుకుంటున్నాము',
    absButton: 'ABS అనుసరణను పరిశీలించండి',
    absEmpty: 'ABS చెక్‌లిస్ట్‌ను చూడటానికి పైన ఉత్పత్తి లేదా సోర్సింగ్ దృశ్యాన్ని వివరించండి.',
    absNotTriggered: 'ఈ ప్రశ్న కోసం స్పష్టమైన యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ సంకేతం కనుగొనబడలేదు. ఇది ABSను పూర్తిగా తోసిపుచ్చదు — మరింత నిర్దిష్టమైన పరిశీలన కోసం జీవ వనరు మరియు దాని మూలాన్ని వివరించండి.',

    tkdlTitle: 'TKDL / ముందస్తు-కళ పరిశీలన',
    tkdlLede: 'శాస్త్రీయ సూత్రీకరణకు సంబంధించిన సాంప్రదాయ జ్ఞాన డిజిటల్ లైబ్రరీ వర్క్‌ఫ్లోను సూచిస్తుంది మరియు వ్యవస్థ కనుగొన్న ముందస్తు-కళ మూలాలను చూపిస్తుంది.',
    tkdlPlaceholder: 'ఉదా. ఈ సూత్రీకరణ ఇప్పటికే ఒక శాస్త్రీయ గ్రంథంలో సాంప్రదాయ జ్ఞానంగా నమోదు చేయబడిందా?',
    tkdlButton: 'TKDL / ముందస్తు-కళను పరిశీలించండి',
    tkdlEmpty: 'సాంప్రదాయ జ్ఞాన సూచన మరియు సంబంధిత మూలాలను చూడటానికి పైన సూత్రీకరణను వివరించండి.',
    tkdlNotTriggered: 'ఈ ప్రశ్న కోసం సాంప్రదాయ జ్ఞాన సూచన రూపొందించబడలేదు — ఇది శాస్త్రీయ/సాధారణంగా వర్గీకరించబడకపోవచ్చు, లేదా TK-సంబంధిత మూలం పొందబడలేదు.',

    languageEnglish: 'ఇంగ్లీష్', languageTelugu: 'తెలుగు', languageHindi: 'హిందీ', primaryNavigation: 'ప్రధాన నావిగేషన్', loadingAnalysis: 'విశ్లేషణ లోడ్ అవుతోంది',
    analysisHelper: 'ఎంచుకున్న అధికార పరిధిలో ఆధారాలతో కూడిన విశ్లేషణ', jurisdictionPrefix: 'అధికార పరిధి',
    clarificationCategories: ['శాస్త్రీయ / సాధారణ ఔషధం', 'పేటెంట్ / స్వంత ఔషధం', 'కొత్త / శాస్త్రీయేతర ఔషధం', 'ఫైటోఫార్మాస్యూటికల్', 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', 'కాస్మెటిక్'],
    paraphraseVerified: 'Groq ద్వారా రూపుదిద్దబడింది · ఉల్లేఖనలు ధృవీకరించబడ్డాయి', translationUnavailableAnswer: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సమాధానం చూపబడుతోంది.',
    tkPointer: 'సాంప్రదాయ జ్ఞానం / ముందస్తు-కళ సూచన', absConsiderations: 'సంభావ్య ABS పరిశీలనలు',
    absChecklist: { biologicalResource: 'జీవ వనరు ఉంది', provenance: 'మూలం / ప్రోవెనెన్స్ గుర్తించబడింది', framework: 'సంబంధిత ABS ఫ్రేమ్‌వర్క్ గుర్తించబడింది', source: 'మద్దతు మూలం పొందబడింది' },
    confidenceSupport: 'నిలుపుకున్న మూలాలు ఈ విశ్లేషణకు ఎంత బలంగా మద్దతు ఇస్తున్నాయి', compositeConfidence: 'సమ్మిళిత విశ్వసనీయత', confidenceScale: 'విశ్వసనీయత స్థాయి',
    confidenceFactors: { retrieval_relevance: 'రిట్రీవల్ సంబంధితత', source_count_factor: 'మూలాల సంఖ్య', source_authority: 'మూల అధికారికత', agreement: 'డొమైన్ సమ్మతి', classification_confidence: 'వర్గీకరణ విశ్వసనీయత' },
    confidenceNote: 'ఈ విశ్లేషణలో నిజంగా ఉత్పత్తి అయిన రిట్రీవల్ మరియు వర్గీకరణ సంకేతాల ఆధారంగా సమ్మిళిత స్కోరు లెక్కించబడుతుంది — కల్పిత ఖచ్చితత్వం కాదు.',
    translationUnavailableMessage: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సందేశం చూపబడుతోంది.', evidenceBoundaryReason: 'నిలుపుకున్న ఆధారాల సమితి ఖాళీగా ఉంది లేదా దాని సమ్మిళిత విశ్వసనీయత సురక్షిత సమాధాన పరిమితి కంటే తక్కువగా ఉంది — అందువల్ల వ్యవస్థ ఊహించి సమాధానం ఇవ్వడం లేదు.',
    sourceLabel: 'మూలం', matchLabel: 'సరిపోలిక', sourceFields: { authority: 'అధికారికత', domain: 'డొమైన్', type: 'మూల రకం', version: 'వెర్షన్', retrieved: 'పొందిన తేదీ', precision: 'ఖచ్చితత్వం' }, viewSource: 'మూలాన్ని చూడండి',
    builtFor: 'ఆయుష్ మంత్రిత్వ శాఖ & ఆల్ ఇండియా ఇన్‌స్టిట్యూట్ ఆఫ్ ఆయుర్వేదం కోసం నిర్మించబడింది', liveEvidenceTrail: 'ప్రత్యక్ష ఆధార మార్గం', heroTraceTitle: 'ఉత్పత్తి నుండి నిబంధన వరకు, మొత్తం మార్గం కనిపిస్తుంది.', heroTraceBody: 'SUTRADHARA ప్రశ్నను వర్గీకరిస్తుంది, సంబంధిత పాలనకు మార్గనిర్దేశం చేస్తుంది మరియు మూలాన్ని చూపిస్తుంది.', citationGrounded: 'ఉల్లేఖన ఆధారితం',
    heroTrace: [{ label: 'ఉత్పత్తి ప్రశ్న', value: 'కొత్త ప్రక్రియతో అశ్వగంధ సారం' }, { label: 'వర్గీకరణ', value: 'ఫైటోఫార్మాస్యూటికల్ / జీవ వనరు' }, { label: 'ఆధార మార్గం', value: 'జీవ వైవిధ్య చట్టం, 2002 · సెక్షన్ 7' }], sourceRetained: 'మూలం నిలుపబడింది', confidenceHigh: 'విశ్వసనీయత: అధిక',
    focusedTool: 'కేంద్రీకృత పరిశోధన సాధనం', working: 'పని జరుగుతోంది…', absChecklistLabel: 'ABS చెక్‌లిస్ట్', tkdlPointerLabel: 'TKDL సూచన', preview: 'పరిదృశ్యం',
    reviewPathway: 'మానవ సమీక్ష మార్గం', escalateTitle: 'IP సదుపాయకుడికి పంపండి', escalationDescription: 'మానవ సదుపాయకుడు ఈ ప్రశ్నను మరియు దిగువ పొందిన ఆధారాలను సమీక్షిస్తారు.', escalationRecorded: 'ఎస్కలేషన్ నమోదు చేయబడింది.', escalationFollowUp: 'దిగువ సందర్భాన్ని ఉపయోగించి సదుపాయకుడు మిమ్మల్ని సంప్రదిస్తారు.',
    escalationFields: { query: 'ప్రశ్న', category: 'వర్గం', jurisdiction: 'అధికార పరిధి', areas: 'అంశాలు', sources: 'మూలాలు' }, noSources: 'ఏవీ లేవు', contactEmail: 'సంప్రదింపు ఇమెయిల్ (ఐచ్ఛికం)', emailPlaceholder: 'you@example.com', escalationError: 'ఎస్కలేషన్ సేవను చేరుకోలేకపోయాం — మళ్లీ ప్రయత్నించండి.', cancel: 'రద్దు', sending: 'పంపుతోంది…', submit: 'సమర్పించండి',
    graphGrounding: 'సమాధానం ఎలా ఆధారపడింది', explainabilityGraph: 'వివరణాత్మక గ్రాఫ్', graphLegend: { query: 'ప్రశ్న సందర్భం', regulatory: 'నియంత్రణ నిర్మాణం', traditional: 'సాంప్రదాయ జ్ఞానం', authoritative: 'అధికారిక మూలం' },
    classificationCategories: { 'Classical / Generic Medicine': 'శాస్త్రీయ / సాధారణ ఔషధం', 'Patent / Proprietary Medicine': 'పేటెంట్ / స్వంత ఔషధం', 'New / Non-Classical Drug': 'కొత్త / శాస్త్రీయేతర ఔషధం', Phytopharmaceutical: 'ఫైటోఫార్మాస్యూటికల్', 'Ayurveda-Aahar / Nutraceutical': 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', Cosmetic: 'కాస్మెటిక్' }, areaLabels: { Patents: 'పేటెంట్లు', 'Geographical Indications': 'భౌగోళిక సూచనలు', Trademarks: 'ట్రేడ్‌మార్క్‌లు', Copyright: 'కాపీరైట్', Designs: 'డిజైన్లు', 'Trade Secrets': 'వాణిజ్య రహస్యాలు', 'Plant Variety Protection': 'మొక్కల రకం రక్షణ', 'Traditional Knowledge': 'సాంప్రదాయ జ్ఞానం', 'Access-and-Benefit-Sharing': 'యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్', 'Drug regulation': 'ఔషధ నియంత్రణ', Advertising: 'ప్రకటనలు', Labelling: 'లేబులింగ్', 'Food / nutraceutical regulation': 'ఆహార / న్యూట్రాస్యూటికల్ నియంత్రణ', 'Cosmetic regulation': 'కాస్మెటిక్ నియంత్రణ' },
    graphNodes: { product: 'ఆయుర్వేద ఉత్పత్తి', category: 'ఉత్పత్తి వర్గం', tk: 'సాంప్రదాయ జ్ఞానం', regime: 'IP / నియంత్రణ పాలన', law: 'పాలక చట్టం', provision: 'నిబంధన', source: 'అధికారిక మూలం' }, graphEdges: { product_category: 'చెందుతుంది', category_regime: 'సంబంధితం', category_tk: 'సూచించవచ్చు', regime_law: 'చట్టం ద్వారా పాలితం', law_provision: 'కలిగి ఉంది', provision_source: 'మూలం మద్దతు' },
    eval: { observability: 'వ్యవస్థ పరిశీలన', title: 'మూల్యాంకన డ్యాష్‌బోర్డ్', chartLabel: 'విశ్వసనీయత చరిత్ర చార్ట్', chartTitle: 'లాగ్ చేసిన ప్రశ్నల విశ్వసనీయత', observations: 'పరిశీలనలు', chartEmpty: 'మొదటి విశ్లేషణ తర్వాత విశ్వసనీయత చరిత్ర ఇక్కడ కనిపిస్తుంది.', queryStart: 'ప్రశ్న 01', queryLatest: 'తాజా ప్రశ్న', totalQueries: 'మొత్తం లాగ్ చేసిన ప్రశ్నలు', safeAbstention: 'సురక్షిత నిరాకరణ రేటు', averageConfidence: 'సగటు విశ్వసనీయత', answerAccuracy: 'సమాధాన ఖచ్చితత్వం', citationCorrectness: 'ఉల్లేఖన ఖచ్చితత్వం', classificationAccuracy: 'వర్గీకరణ ఖచ్చితత్వం', multilingualQuality: 'బహుభాషా సమాధాన నాణ్యత', pending: 'మూల్యాంకనం పెండింగ్‌లో ఉంది', manualReviewSet: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — ధృవీకరించిన పరీక్షా సమితితో మానవ సమీక్ష అవసరం', manualReview: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — మానవ సమీక్ష అవసరం', emptyTitle: 'మీ ఆధార మార్గం ఇక్కడ ప్రారంభమవుతుంది.', emptyBody: 'విశ్వసనీయత చరిత్ర, ఉల్లేఖన తనిఖీలు మరియు వర్గీకరణ సమీక్షను నింపడానికి విశ్లేషణ నడపండి.', citationReview: 'ఉల్లేఖన సమీక్ష', note: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — ఇంకా ప్రశ్నలు లాగ్ కాలేదు.' },
  },
  hi: {
    appName: 'सूत्रधार',
    tagline: 'आयुर्वेद के लिए AI-संचालित IP और नियामक बुद्धिमत्ता',
    team: 'टीम चातुर्य',
    heroLede: 'यह मंच आयुर्वेदिक उत्पादों को लागू बौद्धिक संपदा व्यवस्थाओं, नियामक आवश्यकताओं, क्षेत्राधिकार-विशिष्ट नियमों और आधिकारिक प्रमाणों से जोड़ता है।',
    heroCta: 'आयुर्वेदिक उत्पाद का विश्लेषण करें',

    navAnalyze: 'विश्लेषण',
    navAbs: 'ABS अनुपालन',
    navTkdl: 'TKDL जांच',
    navEvidence: 'प्रमाण',
    navGraph: 'ज्ञान ग्राफ',
    navEval: 'मूल्यांकन',

    inputLabel: 'अपने आयुर्वेदिक उत्पाद या IP प्रश्न का वर्णन करें',
    placeholder: 'उदा. क्या पारंपरिक ग्रंथ में वर्णित शास्त्रीय आयुर्वेदिक फॉर्मूलेशन का पेटेंट लिया जा सकता है?',
    analyze: 'विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है…',
    india: 'भारत',
    international: 'अंतरराष्ट्रीय',
    disclaimer: 'यह जानकारी है, कानूनी सलाह नहीं।',
    classification: 'उत्पाद वर्गीकरण',
    jurisdiction: 'क्षेत्राधिकार',
    applicableAreas: 'लागू IP और नियामक क्षेत्र',
    assessment: 'AI आकलन',
    sources: 'प्रमाण और उद्धरण',
    confidence: 'प्रमाण विश्वसनीयता',
    escalate: 'IP सुविधा केंद्र को भेजें',
    needExpert: 'विशेषज्ञ सहायता चाहिए?',
    detectedLanguage: 'पहचानी गई इनपुट भाषा',
    retrievalNote: 'रिट्रीवल के लिए सामान्यीकृत',
    evidenceBoundary: 'प्रमाण सीमा',
    evidenceBoundaryBody: 'विश्वसनीय उत्तर देने के लिए पर्याप्त आधिकारिक प्रमाण उपलब्ध नहीं है।',
    whyAbstained: 'प्रणाली ने उत्तर क्यों रोका',
    systemError: 'विश्लेषण सेवा अभी अस्थायी रूप से अनुपलब्ध है। कृपया कुछ देर बाद फिर प्रयास करें।',

    evidencePageTitle: 'प्रमाण अन्वेषक',
    evidencePageLede: 'पिछला उत्तर कहाँ से आया? नीचे दिया गया प्रत्येक स्रोत आपके नवीनतम विश्लेषण के लिए आधिकारिक कॉर्पस से प्राप्त किया गया है।',
    evidenceEmpty: 'पहले विश्लेषण चलाएँ — उस प्रश्न के प्राप्त स्रोत यहाँ दिखाई देंगे।',

    graphEmpty: 'इस समय बैकएंड से ज्ञान ग्राफ डेटा उपलब्ध नहीं है।',
    evalEmpty: 'इस सत्र में अभी तक कोई प्रश्न लॉग नहीं हुआ है।',

    absTitle: 'ABS अनुपालन जांच',
    absLede: 'यह जांचता है कि कोई प्रश्न जैव विविधता अधिनियम, CBD और नागोया प्रोटोकॉल के तहत Access-and-Benefit-Sharing दायित्व शुरू कर सकता है या नहीं।',
    absPlaceholder: 'उदा. हम भारत के किसी क्षेत्र से प्राप्त जैविक संसाधन का उपयोग करने वाले फॉर्मूलेशन का व्यावसायीकरण करना चाहते हैं',
    absButton: 'ABS अनुपालन जांचें',
    absEmpty: 'ABS चेकलिस्ट देखने के लिए ऊपर उत्पाद या सोर्सिंग स्थिति का वर्णन करें।',
    absNotTriggered: 'इस प्रश्न में ABS का स्पष्ट संकेत नहीं मिला। यह ABS को पूरी तरह नकारता नहीं है — अधिक विशिष्ट जांच के लिए जैविक संसाधन और उसका स्रोत बताएं।',

    tkdlTitle: 'TKDL / पूर्व कला जांच',
    tkdlLede: 'यह शास्त्रीय फॉर्मूलेशन से संबंधित Traditional Knowledge Digital Library प्रक्रिया और मिले हुए पूर्व कला स्रोत दिखाता है।',
    tkdlPlaceholder: 'उदा. क्या यह फॉर्मूलेशन पहले से किसी शास्त्रीय ग्रंथ में पारंपरिक ज्ञान के रूप में दर्ज है?',
    tkdlButton: 'TKDL / पूर्व कला जांचें',
    tkdlEmpty: 'TKDL संकेत और संबंधित स्रोत देखने के लिए ऊपर फॉर्मूलेशन का वर्णन करें।',
    tkdlNotTriggered: 'इस प्रश्न के लिए पारंपरिक ज्ञान संकेत नहीं बनाया गया — यह शास्त्रीय/सामान्य श्रेणी में नहीं आता हो सकता है या कोई संबंधित स्रोत नहीं मिला।',

    languageEnglish: 'अंग्रेज़ी', languageTelugu: 'तेलुगु', languageHindi: 'हिन्दी', primaryNavigation: 'मुख्य नेविगेशन', loadingAnalysis: 'विश्लेषण लोड हो रहा है',
    analysisHelper: 'चयनित क्षेत्राधिकार में प्रमाण-आधारित विश्लेषण', jurisdictionPrefix: 'क्षेत्राधिकार',
    clarificationCategories: ['शास्त्रीय / सामान्य औषधि', 'पेटेंट / स्वामित्व वाली औषधि', 'नई / गैर-शास्त्रीय औषधि', 'फाइटोफार्मास्यूटिकल', 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', 'कॉस्मेटिक'],
    paraphraseVerified: 'Groq द्वारा रूपांतरित · उद्धरण सत्यापित', translationUnavailableAnswer: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी उत्तर दिखाया जा रहा है।',
    tkPointer: 'पारंपरिक ज्ञान / पूर्व कला संकेत', absConsiderations: 'संभावित ABS विचार',
    absChecklist: { biologicalResource: 'जैविक संसाधन शामिल है', provenance: 'स्रोत / उत्पत्ति पहचानी गई', framework: 'संबंधित ABS ढांचा पहचाना गया', source: 'समर्थन स्रोत प्राप्त हुआ' },
    confidenceSupport: 'रखे गए स्रोत इस विश्लेषण का कितना मजबूत समर्थन करते हैं', compositeConfidence: 'समग्र विश्वसनीयता', confidenceScale: 'विश्वसनीयता पैमाना',
    confidenceFactors: { retrieval_relevance: 'रिट्रीवल प्रासंगिकता', source_count_factor: 'स्रोत संख्या', source_authority: 'स्रोत की प्रामाणिकता', agreement: 'डोमेन सहमति', classification_confidence: 'वर्गीकरण विश्वसनीयता' },
    confidenceNote: 'समग्र स्कोर इस विश्लेषण से प्राप्त रिट्रीवल और वर्गीकरण संकेतों से बनाया जाता है — यह कोई गढ़ी हुई सटीकता नहीं है।',
    translationUnavailableMessage: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी संदेश दिखाया जा रहा है।', evidenceBoundaryReason: 'रखे गए प्रमाण खाली थे या उनकी संयुक्त विश्वसनीयता सुरक्षित उत्तर सीमा से कम थी — इसलिए प्रणाली अनुमान लगाकर उत्तर देने से इनकार कर रही है।',
    sourceLabel: 'स्रोत', matchLabel: 'मिलान', sourceFields: { authority: 'प्राधिकरण', domain: 'डोमेन', type: 'स्रोत प्रकार', version: 'संस्करण', retrieved: 'प्राप्त', precision: 'सटीकता' }, viewSource: 'स्रोत देखें',
    builtFor: 'आयुष मंत्रालय और अखिल भारतीय आयुर्वेद संस्थान के लिए निर्मित', liveEvidenceTrail: 'एक जीवंत प्रमाण मार्ग', heroTraceTitle: 'उत्पाद से प्रावधान तक, पूरी श्रृंखला दिखाई देती है।', heroTraceBody: 'SUTRADHARA प्रश्न को वर्गीकृत करता है, संबंधित व्यवस्था तक पहुँचाता है और स्रोत को सामने रखता है।', citationGrounded: 'उद्धरण-आधारित प्रणाली',
    heroTrace: [{ label: 'उत्पाद प्रश्न', value: 'नई प्रक्रिया वाला अश्वगंधा अर्क' }, { label: 'वर्गीकरण', value: 'फाइटोफार्मास्यूटिकल / जैविक संसाधन' }, { label: 'प्रमाण मार्ग', value: 'जैव विविधता अधिनियम, 2002 · धारा 7' }], sourceRetained: 'स्रोत सुरक्षित', confidenceHigh: 'विश्वसनीयता: उच्च',
    focusedTool: 'केंद्रित शोध उपकरण', working: 'काम हो रहा है…', absChecklistLabel: 'ABS चेकलिस्ट', tkdlPointerLabel: 'TKDL संकेत', preview: 'पूर्वावलोकन',
    reviewPathway: 'मानव समीक्षा मार्ग', escalateTitle: 'IP सुविधा केंद्र को भेजें', escalationDescription: 'एक मानव सुविधाकर्ता नीचे प्राप्त प्रमाणों के साथ इस प्रश्न की समीक्षा करेगा।', escalationRecorded: 'एस्केलेशन दर्ज हो गया है।', escalationFollowUp: 'सुविधाकर्ता नीचे दिए गए संदर्भ के आधार पर आपसे संपर्क करेगा।',
    escalationFields: { query: 'प्रश्न', category: 'श्रेणी', jurisdiction: 'क्षेत्राधिकार', areas: 'क्षेत्र', sources: 'स्रोत' }, noSources: 'कोई नहीं', contactEmail: 'संपर्क ईमेल (वैकल्पिक)', emailPlaceholder: 'you@example.com', escalationError: 'एस्केलेशन सेवा तक नहीं पहुँच सके — कृपया फिर प्रयास करें।', cancel: 'रद्द करें', sending: 'भेजा जा रहा है…', submit: 'जमा करें',
    graphGrounding: 'उत्तर किस तरह प्रमाणित है', explainabilityGraph: 'व्याख्यात्मक ग्राफ', graphLegend: { query: 'प्रश्न संदर्भ', regulatory: 'नियामक संरचना', traditional: 'पारंपरिक ज्ञान', authoritative: 'आधिकारिक स्रोत' },
    classificationCategories: { 'Classical / Generic Medicine': 'शास्त्रीय / सामान्य औषधि', 'Patent / Proprietary Medicine': 'पेटेंट / स्वामित्व वाली औषधि', 'New / Non-Classical Drug': 'नई / गैर-शास्त्रीय औषधि', Phytopharmaceutical: 'फाइटोफार्मास्यूटिकल', 'Ayurveda-Aahar / Nutraceutical': 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', Cosmetic: 'कॉस्मेटिक' }, areaLabels: { Patents: 'पेटेंट', 'Geographical Indications': 'भौगोलिक संकेत', Trademarks: 'ट्रेडमार्क', Copyright: 'कॉपीराइट', Designs: 'डिज़ाइन', 'Trade Secrets': 'व्यापार रहस्य', 'Plant Variety Protection': 'पादप किस्म संरक्षण', 'Traditional Knowledge': 'पारंपरिक ज्ञान', 'Access-and-Benefit-Sharing': 'लाभ-साझाकरण', 'Drug regulation': 'औषधि नियमन', Advertising: 'विज्ञापन', Labelling: 'लेबलिंग', 'Food / nutraceutical regulation': 'खाद्य / न्यूट्रास्यूटिकल नियमन', 'Cosmetic regulation': 'कॉस्मेटिक नियमन' },
    graphNodes: { product: 'आयुर्वेदिक उत्पाद', category: 'उत्पाद श्रेणी', tk: 'पारंपरिक ज्ञान', regime: 'IP / नियामक व्यवस्था', law: 'शासी कानून', provision: 'प्रावधान', source: 'आधिकारिक स्रोत' }, graphEdges: { product_category: 'का हिस्सा है', category_regime: 'संबंधित है', category_tk: 'संदर्भित कर सकता है', regime_law: 'कानून द्वारा शासित', law_provision: 'इसमें शामिल है', provision_source: 'स्रोत द्वारा समर्थित' },
    eval: { observability: 'प्रणाली अवलोकन', title: 'मूल्यांकन डैशबोर्ड', chartLabel: 'विश्वसनीयता इतिहास चार्ट', chartTitle: 'लॉग किए गए प्रश्नों की विश्वसनीयता', observations: 'अवलोकन', chartEmpty: 'पहले विश्लेषण के बाद विश्वसनीयता इतिहास यहाँ दिखाई देगा।', queryStart: 'प्रश्न 01', queryLatest: 'नवीनतम प्रश्न', totalQueries: 'लॉग किए गए कुल प्रश्न', safeAbstention: 'सुरक्षित उत्तर-त्याग दर', averageConfidence: 'औसत विश्वसनीयता', answerAccuracy: 'उत्तर सटीकता', citationCorrectness: 'उद्धरण शुद्धता', classificationAccuracy: 'वर्गीकरण सटीकता', multilingualQuality: 'बहुभाषी उत्तर गुणवत्ता', pending: 'मूल्यांकन लंबित है', manualReviewSet: 'मूल्यांकन लंबित है — सत्यापित परीक्षण सेट के साथ मानव समीक्षा आवश्यक है', manualReview: 'मूल्यांकन लंबित है — मानव समीक्षा आवश्यक है', emptyTitle: 'आपका प्रमाण मार्ग यहाँ से शुरू होता है।', emptyBody: 'विश्वसनीयता इतिहास, उद्धरण जांच और वर्गीकरण समीक्षा भरने के लिए विश्लेषण चलाएँ।', citationReview: 'उद्धरण समीक्षा', note: 'मूल्यांकन लंबित है — अभी कोई प्रश्न लॉग नहीं हुआ है।' },
  },
}
